<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.0.0.3</Version>
    <PackageProjectUrl>https://github.com/Catphinaud/SelectNextLootItem</PackageProjectUrl>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AppendPlatformToOutputPath>false</AppendPlatformToOutputPath>
  </PropertyGroup>
</Project>
